[package]
name = "shell"
edition = "2024"
publish = false
default-run = "shell"

[[bin]]
name = "shell"

[[bin]]
name = "shell_helper"
path = "src/mac/helper.rs"

[[bin]]
name = "bundle_shell"
path = "src/mac/bundle_shell.rs"

[[bin]]
name = "package_shell"
path = "src/package.rs"

[features]
default = ["sandbox"]
sandbox = ["cef/sandbox"]

[dependencies]
cef.workspace = true
cef-dll-sys.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_Storage_FileSystem",
    "Win32_System_Pipes",
    "Win32_Security",
    "Win32_System_IO",
] }

[target.'cfg(target_os = "macos")'.dependencies]
plist.workspace = true
serde.workspace = true
objc2.workspace = true
objc2-app-kit = { workspace = true, features = ["NSApplication", "NSResponder"] }

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3"
